export type Lang = "en" | "pl";

const en = {
  langSwitch: "PL",
  langAria: "Switch language to Polish",
  themeDark: "Dark",
  themeLight: "Light",
  themeAria: "Toggle light and dark theme",
  a11y: {
    newTab: "opens in a new tab",
    download: "downloads a file",
  },
  reposTitle: "More on GitHub",
  repos: [
    {
      name: "columbus-shop",
      body: "An online shop built with Next.js and TypeScript.",
      stack: "Next.js · TypeScript",
      link: "https://github.com/martynakweczke/columbus-shop",
    },
    {
      name: "epam-angular-courses-app",
      body: "Courses app from EPAM's Angular Frontend Specialization program.",
      stack: "Angular · TypeScript",
      link: "https://github.com/martynakweczke/epam-angular-courses-app",
    },
  ],
  nav: [
    { label: "Work", href: "#work" },
    { label: "Experience", href: "#experience" },
    { label: "Skills", href: "#skills" },
    { label: "Credentials", href: "#credentials" },
    { label: "Contact", href: "#contact" },
  ],
  hero: {
    kicker: "Junior frontend & full-stack developer — Wrocław, Poland",
    lede: "Over a year of hands-on experience in Angular, React and TypeScript. I build clean, user-friendly interfaces, care about code quality more than speed, and use AI agents and LLMs as tools that let me learn faster — not as shortcuts around understanding.",
    available: "Open to junior roles",
    ctaMail: "Get in touch",
    ctaCv: "Download CV",
  },
  now: [
    { k: "Currently", v: "Junior full-stack developer at beefity" },
    { k: "Based in", v: "Wrocław, Poland — on-site, hybrid or remote" },
    { k: "Working with", v: "Angular · React · TypeScript" },
  ],
  work: { title: "Selected work", kicker: "Projects" },
  projects: [
    {
      title: "beefity",
      badge: "Current",
      meta: "Junior full-stack developer · 2025, 2026 — present",
      body: "A web and mobile app for people who work out and for their trainers. I started here implementing screens in JavaScript, HTML and CSS, and came back as a junior full-stack developer — now also working through the NestJS and SQL side of the product.",
      tags: ["React", "React Native", "Expo", "TypeScript", "Nativewind", "NestJS", "SQL"],
      link: "https://beefity.com/",
      linkLabel: "beefity.com",
    },
    {
      title: "Angular platform migration",
      badge: "",
      meta: "Rokezzz · frontend developer · 2026-05 — 2026-09",
      body: "Migrated a customer-facing application to the latest Angular version and refactored it on the way, inside a cross-functional Scrum team: translating UI/UX designs into features, checking their technical feasibility and integrating REST APIs.",
      tags: ["Angular", "RxJS", "TypeScript", "SCSS", "REST", "Git"],
      link: "",
      linkLabel: "",
    },
    {
      title: "EPAM capstone project",
      badge: "",
      meta: "Frontend Development Program · 2025",
      body: "The closing project of EPAM's Frontend Development Program — built from scratch with HTML, CSS, JavaScript and TypeScript, and held to the program's linting, review and code-quality standards.",
      tags: ["JavaScript", "TypeScript", "HTML", "SCSS", "ESLint", "SonarQube"],
      link: "https://github.com/martynakweczke/epam-frontend-development-program",
      linkLabel: "View repository",
    },
    {
      title: "Programming language quiz",
      badge: "In progress",
      meta: "Personal project · 2026",
      body: "A site for testing your knowledge of web technologies — JavaScript, TypeScript, HTML and CSS to start with, more to follow. Being built with Next.js, React and Tailwind; the link will appear here once it ships.",
      tags: ["Next.js", "React", "TypeScript", "Tailwind"],
      link: "",
      linkLabel: "",
    },
    {
      title: "This portfolio",
      badge: "",
      meta: "Personal project · 2026",
      body: "This site: built with Next.js and React and styled with Tailwind, responsive, bilingual and with a light and dark theme. The source lives in a public repository, so you can read the code as well as the page.",
      tags: ["Next.js", "React", "TypeScript", "Tailwind", "i18n"],
      link: "https://github.com/martynakweczke",
      linkLabel: "View source",
    },
  ],
  exp: { title: "Experience", kicker: "Work history" },
  jobs: [
    {
      period: "2026 — present",
      role: "Junior Full-Stack Developer",
      org: "beefity",
      body: "Back on the beefity product, now working across the stack rather than only on screens.",
      tags: ["React", "React Native", "TypeScript", "NestJS", "SQL", "Git"],
    },
    {
      period: "2026-05 — 2026-09",
      role: "Frontend Developer (Angular)",
      org: "Rokezzz · intern program",
      body: "Implemented and refactored a customer-facing application while migrating it to the latest Angular version, following UI/UX best practices and delivering features with an agile, cross-functional team.",
      tags: ["Angular", "RxJS", "TypeScript", "SCSS", "REST", "Figma", "Jira", "Scrum"],
    },
    {
      period: "2026-01 — 2026-04",
      role: "Frontend Specialization Program Trainee",
      org: "EPAM Systems",
      body: "Deepening Angular skills and the tooling around them — state management with NgRx, reactive streams with RxJS, and code quality enforced by SonarQube, ESLint, Stylelint and peer review.",
      tags: ["Angular", "NgRx", "RxJS", "TypeScript", "SonarQube", "GitLab"],
    },
    {
      period: "2025-09 — 2025-12",
      role: "Frontend Development Program Trainee",
      org: "EPAM Systems",
      body: "Modern web fundamentals — HTML, CSS, SCSS, JavaScript and TypeScript — closed with a capstone project reviewed against the program's standards.",
      tags: ["JavaScript", "TypeScript", "HTML", "CSS", "SCSS", "Git"],
    },
    {
      period: "2025-04 — 2025-08",
      role: "Entry-level Frontend Developer",
      org: "beefity",
      body: "First professional steps: implementing screens for a mobile and web fitness app, and learning to read and navigate a NestJS and SQL backend.",
      tags: ["JavaScript", "React.js", "React Native", "Tailwind", "Expo", "REST"],
    },
  ],
  before: {
    title: "Before development",
    body: "Three years of customer-facing work before the switch: bank employee at Millennium (2023 — 2024), where I walked customers through online and mobile banking, handled escalations and monitored accounts for suspicious activity; and cafeteria worker at Habza Cafe (2021 — 2023), where I also ran the social media accounts. That is where I learned to explain technical things in plain language and stay precise under pressure — most of the job in code review and stakeholder calls, too.",
  },
  skills: { title: "Skills & tools", kicker: "Stack" },
  skillGroups: [
    {
      title: "Frameworks & libraries",
      items: ["Angular", "React", "Next.js", "React Native", "RxJS", "NgRx", "Expo"],
    },
    {
      title: "Languages & styling",
      items: ["TypeScript", "JavaScript", "HTML", "CSS", "SCSS", "Tailwind / Nativewind"],
    },
    {
      title: "Tooling & practice",
      items: [
        "Git",
        "GitHub",
        "GitLab",
        "ESLint",
        "Stylelint",
        "Prettier",
        "SonarQube",
        "Code review",
        "REST APIs",
        "Figma",
        "Jira",
        "Scrum",
        "WSL",
      ],
    },
    {
      title: "AI-assisted development",
      items: ["Cursor", "Claude Code", "GitHub Copilot", "ChatGPT", "Gemini"],
    },
  ],
  cred: {
    title: "Certificates & education",
    kicker: "Credentials",
    certs: "Certificates",
    education: "Education",
    languages: "Languages",
  },
  certs: [
    {
      date: "2026-03",
      title: "EngX Bootcamp Course",
      org: "EPAM Systems & EngX Education",
      body: "Foundations of engineering excellence, EngX in development, quality assurance, system engineering and secure SDLC.",
    },
    {
      date: "2026-01",
      title: "Front-End Fundamentals Program",
      org: "EPAM Systems",
      body: "Git, advanced CSS, JavaScript and TypeScript. Credential ID: AAAAB36R.",
    },
    {
      date: "2024-07",
      title: "JavaScript for Beginners — From A to Z",
      org: "Udemy",
      body: "How JavaScript works, the DOM, and current coding techniques.",
    },
    {
      date: "2024-05",
      title: "HTML and CSS Website Implementation — Basics to Expertise",
      org: "Udemy",
      body: "Building and structuring websites from markup to layout.",
    },
    {
      date: "2024-03",
      title: "Programming Fundamentals",
      org: "strefakursow.pl",
      body: "Credential ID: iswbq4z3jdsksswgks0wg8wcc44k8kk",
    },
  ],
  education: [
    {
      period: "2021-10 — 2023-07",
      degree: "Dietetics, Master's degree",
      org: "Wrocław Medical University, Wrocław",
    },
    {
      period: "2018-10 — 2021-07",
      degree: "Dietetics, Bachelor's degree",
      org: "Medical University of Silesia, Katowice",
    },
  ],
  langs: [
    { name: "Polish", level: "C2 — native" },
    { name: "English", level: "B2" },
  ],
  personal: {
    kicker: "Personal",
    title: "Beyond the code",
    body: "I came to development from dietetics, and the two have more in common than they look: both are about reading a system carefully before changing anything. Outside work I train, walk in the mountains and look after a very demanding dog — the same routine that keeps me patient with a stubborn bug.",
  },
  hobbies: ["Gym and a healthy lifestyle", "Hiking in the mountains", "Taking care of my lovely dog"],
  contact: {
    kicker: "Contact",
    title: "Let's talk.",
    body: "I'm looking for a junior frontend or full-stack role where I can keep learning from people who care about their craft. Email is the fastest way to reach me.",
    cv: "Curriculum vitae",
    footer: "© 2026 Martyna Kweczke · Wrocław, Poland",
  },
};

export type Copy = typeof en;

const pl: Copy = {
  langSwitch: "EN",
  langAria: "Zmień język na angielski",
  themeDark: "Ciemny",
  themeLight: "Jasny",
  themeAria: "Przełącz motyw jasny i ciemny",
  a11y: {
    newTab: "otwiera się w nowej karcie",
    download: "pobiera plik",
  },
  reposTitle: "Więcej na GitHubie",
  repos: [
    {
      name: "columbus-shop",
      body: "Sklep internetowy zbudowany w Next.js i TypeScripcie.",
      stack: "Next.js · TypeScript",
      link: "https://github.com/martynakweczke/columbus-shop",
    },
    {
      name: "epam-angular-courses-app",
      body: "Aplikacja z kursami z programu EPAM Angular Frontend Specialization.",
      stack: "Angular · TypeScript",
      link: "https://github.com/martynakweczke/epam-angular-courses-app",
    },
    {
      name: "epam-frontend-development-program",
      body: "Projekt końcowy stażu EPAM Frontend Development.",
      stack: "TypeScript · HTML · SCSS",
      link: "https://github.com/martynakweczke/epam-frontend-development-program",
    },
    {
      name: "vite-project",
      body: "Projekt końcowy przeniesiony na Vite.",
      stack: "Vite · HTML",
      link: "https://github.com/martynakweczke/vite-project",
    },
  ],
  nav: [
    { label: "Projekty", href: "#work" },
    { label: "Doświadczenie", href: "#experience" },
    { label: "Umiejętności", href: "#skills" },
    { label: "Kwalifikacje", href: "#credentials" },
    { label: "Kontakt", href: "#contact" },
  ],
  hero: {
    kicker: "Junior frontend & full-stack developer — Wrocław",
    lede: "Ponad rok praktycznego doświadczenia w Angularze, Reakcie i TypeScripcie. Tworzę czyste, przyjazne użytkownikowi interfejsy, jakość kodu stawiam wyżej niż tempo, a agentów AI i modele językowe traktuję jako narzędzia do szybszej nauki — nie jako skrót zamiast zrozumienia.",
    available: "Otwarta na oferty junior",
    ctaMail: "Napisz do mnie",
    ctaCv: "Pobierz CV",
  },
  now: [
    { k: "Obecnie", v: "Junior full-stack developer w beefity" },
    { k: "Lokalizacja", v: "Wrocław — praca w biurze, hybrydowa lub zdalna" },
    { k: "Technologie", v: "Angular · React · TypeScript" },
  ],
  work: { title: "Wybrane projekty", kicker: "Projekty" },
  projects: [
    {
      title: "beefity",
      badge: "Obecnie",
      meta: "Junior full-stack developer · 2025, 2026 — obecnie",
      body: "Aplikacja webowa i mobilna dla osób trenujących oraz dla trenerów. Zaczynałam tu od implementacji prostych ekranów w JavaScripcie, HTML-u i CSS-ie, a wróciłam jako junior full-stack developer — dziś pracuję również po stronie NestJS i SQL.",
      tags: ["React", "React Native", "Expo", "TypeScript", "Nativewind", "NestJS", "SQL"],
      link: "https://beefity.com/",
      linkLabel: "beefity.com",
    },
    {
      title: "Migracja platformy w Angularze",
      badge: "",
      meta: "Rokezzz · frontend developer · 2026-05 — 2026-09",
      body: "Migracja aplikacji dla klientów do najnowszej wersji Angulara wraz z refaktoryzacją, w interdyscyplinarnym zespole scrumowym: przekładanie projektów UI/UX na funkcje, ocena ich wykonalności technicznej i integracja z REST API.",
      tags: ["Angular", "RxJS", "TypeScript", "SCSS", "REST", "Git"],
      link: "",
      linkLabel: "",
    },
    {
      title: "Projekt końcowy EPAM",
      badge: "",
      meta: "Frontend Development Program · 2025",
      body: "Projekt zamykający program EPAM Frontend Development — zbudowany od zera w HTML-u, CSS-ie, JavaScripcie i TypeScripcie, zgodnie ze standardami lintowania i code review obowiązującymi w programie.",
      tags: ["JavaScript", "TypeScript", "HTML", "SCSS", "ESLint", "SonarQube"],
      link: "https://github.com/martynakweczke/epam-frontend-development-program",
      linkLabel: "Zobacz repozytorium",
    },
    {
      title: "Quiz z języków programowania",
      badge: "W trakcie",
      meta: "Projekt własny · 2026",
      body: "Strona do sprawdzania wiedzy z technologii webowych — na początek JavaScript, TypeScript, HTML i CSS, z czasem więcej. Powstaje w Next.js, Reakcie i Tailwindzie; link pojawi się tutaj po wdrożeniu.",
      tags: ["Next.js", "React", "TypeScript", "Tailwind"],
      link: "",
      linkLabel: "",
    },
    {
      title: "To portfolio",
      badge: "",
      meta: "Projekt własny · 2026",
      body: "Ta strona: zbudowana w Next.js i Reakcie, stylowana Tailwindem, responsywna, dwujęzyczna, z jasnym i ciemnym motywem. Kod źródłowy jest w publicznym repozytorium — można przeczytać nie tylko stronę, ale i kod.",
      tags: ["Next.js", "React", "TypeScript", "Tailwind", "i18n"],
      link: "https://github.com/martynakweczke",
      linkLabel: "Zobacz kod",
    },
  ],
  exp: { title: "Doświadczenie", kicker: "Historia pracy" },
  jobs: [
    {
      period: "2026 — obecnie",
      role: "Junior Full-Stack Developer",
      org: "beefity",
      body: "Powrót do produktu beefity — tym razem praca po obu stronach stosu, nie tylko nad ekranami.",
      tags: ["React", "React Native", "TypeScript", "NestJS", "SQL", "Git"],
    },
    {
      period: "2026-05 — 2026-09",
      role: "Frontend Developer (Angular)",
      org: "Rokezzz · program stażowy",
      body: "Implementacja i refaktoryzacja aplikacji dla klientów wraz z migracją do najnowszej wersji Angulara, zgodnie z dobrymi praktykami UI/UX, w zwinnym, interdyscyplinarnym zespole.",
      tags: ["Angular", "RxJS", "TypeScript", "SCSS", "REST", "Figma", "Jira", "Scrum"],
    },
    {
      period: "2026-01 — 2026-04",
      role: "Frontend Specialization Program Trainee",
      org: "EPAM Systems",
      body: "Pogłębianie Angulara i jego ekosystemu — zarządzanie stanem w NgRx, strumienie w RxJS oraz jakość kodu pilnowana przez SonarQube, ESLint, Stylelint i code review.",
      tags: ["Angular", "NgRx", "RxJS", "TypeScript", "SonarQube", "GitLab"],
    },
    {
      period: "2025-09 — 2025-12",
      role: "Frontend Development Program Trainee",
      org: "EPAM Systems",
      body: "Podstawy nowoczesnego frontendu — HTML, CSS, SCSS, JavaScript i TypeScript — zwieńczone projektem końcowym ocenianym według standardów programu.",
      tags: ["JavaScript", "TypeScript", "HTML", "CSS", "SCSS", "Git"],
    },
    {
      period: "2025-04 — 2025-08",
      role: "Entry-level Frontend Developer",
      org: "beefity",
      body: "Pierwsze zawodowe kroki: implementacja ekranów aplikacji mobilnej i webowej dla osób trenujących oraz czytanie i nawigowanie po backendzie w NestJS i SQL.",
      tags: ["JavaScript", "React.js", "React Native", "Tailwind", "Expo", "REST"],
    },
  ],
  before: {
    title: "Przed programowaniem",
    body: "Trzy lata pracy z klientem przed zmianą branży: doradca w Banku Millennium (2023 — 2024), gdzie tłumaczyłam klientom bankowość internetową i mobilną, prowadziłam trudne rozmowy i monitorowałam podejrzane transakcje, oraz praca w Habza Cafe (2021 — 2023), gdzie prowadziłam też social media. Tam nauczyłam się mówić o technicznych rzeczach prostym językiem i pilnować szczegółów pod presją — czyli w dużej mierze tego samego, co w code review i rozmowach z interesariuszami.",
  },
  skills: { title: "Umiejętności i narzędzia", kicker: "Stack" },
  skillGroups: [
    {
      title: "Frameworki i biblioteki",
      items: ["Angular", "React", "Next.js", "React Native", "RxJS", "NgRx", "Expo"],
    },
    {
      title: "Języki i stylowanie",
      items: ["TypeScript", "JavaScript", "HTML", "CSS", "SCSS", "Tailwind / Nativewind"],
    },
    {
      title: "Narzędzia i praktyki",
      items: [
        "Git",
        "GitHub",
        "GitLab",
        "ESLint",
        "Stylelint",
        "Prettier",
        "SonarQube",
        "Code review",
        "REST API",
        "Figma",
        "Jira",
        "Scrum",
        "WSL",
      ],
    },
    {
      title: "Praca z AI",
      items: ["Cursor", "Claude Code", "GitHub Copilot", "ChatGPT", "Gemini"],
    },
  ],
  cred: {
    title: "Certyfikaty i wykształcenie",
    kicker: "Kwalifikacje",
    certs: "Certyfikaty",
    education: "Wykształcenie",
    languages: "Języki",
  },
  certs: [
    {
      date: "2026-03",
      title: "EngX Bootcamp Course",
      org: "EPAM Systems & EngX Education",
      body: "Podstawy engineering excellence, EngX w programowaniu, QA, inżynierii systemów i bezpiecznym SDLC.",
    },
    {
      date: "2026-01",
      title: "Front-End Fundamentals Program",
      org: "EPAM Systems",
      body: "Git, zaawansowany CSS, JavaScript i TypeScript. ID: AAAAB36R.",
    },
    {
      date: "2024-07",
      title: "JavaScript dla początkujących — od A do Z",
      org: "Udemy",
      body: "Jak działa JavaScript, praca z DOM i aktualne techniki kodowania.",
    },
    {
      date: "2024-05",
      title: "Kurs HTML i CSS — od podstaw do eksperta",
      org: "Udemy",
      body: "Budowa i struktura stron od znaczników do layoutu.",
    },
    {
      date: "2024-03",
      title: "Podstawy programowania",
      org: "strefakursow.pl",
      body: "ID: iswbq4z3jdsksswgks0wg8wcc44k8kk",
    },
  ],
  education: [
    {
      period: "2021-10 — 2023-07",
      degree: "Dietetyka, studia magisterskie",
      org: "Uniwersytet Medyczny we Wrocławiu",
    },
    {
      period: "2018-10 — 2021-07",
      degree: "Dietetyka, studia licencjackie",
      org: "Śląski Uniwersytet Medyczny, Katowice",
    },
  ],
  langs: [
    { name: "Polski", level: "C2 — ojczysty" },
    { name: "Angielski", level: "B2" },
  ],
  personal: {
    kicker: "Prywatnie",
    title: "Poza kodem",
    body: "Do programowania trafiłam z dietetyki, a te dwie dziedziny mają ze sobą więcej wspólnego, niż się wydaje: w obu trzeba uważnie przeczytać system, zanim się w nim cokolwiek zmieni. Po pracy trenuję, chodzę po górach i opiekuję się bardzo wymagającym psem — ta sama rutyna pomaga mi zachować cierpliwość przy upartym bugu.",
  },
  hobbies: ["Siłownia i zdrowy tryb życia", "Górskie wędrówki", "Opieka nad moim ukochanym psem"],
  contact: {
    kicker: "Kontakt",
    title: "Porozmawiajmy.",
    body: "Szukam pracy jako junior frontend lub full-stack developer - w zespole, od którego mogę się uczyć i który dba o jakość tego, co tworzy. Najszybciej odpowiem na e-mail.",
    cv: "Curriculum vitae",
    footer: "© 2026 Martyna Kweczke · Wrocław",
  },
};

export const COPY: Record<Lang, Copy> = { en, pl };
